### ISSUE TITLE
Questions sur le script

### ISSUE THREAD

**Issue by francoisromain** [benefacere/wpgandi#1]
Merci pour ce script. 
j'ai une petite question: 
j'ai l'impression que les E_USAGE=64 et E_BADARGS=65 servent à arréter le script en cas d'erreur. Mais à quoi correspond la valeur 64 et 65 exactement ? 

merci

**Comment by benefacere** [comment]
Ce sont juste des codes erreurs de sortie et ça aurait pu être un code "1" tout simplement (general error). On rencontre parfois cette convention qui propose de mettre ses codes erreurs personnalisés à partir de 64.

**Comment by francoisromain** [comment]
ok merci pour l'explication. : )

Une autre question: qu'est ce qui se passe ici ?

```
 [ $? -eq 0 ]
```
